### ISSUE TITLE
Iniciar el script

### ISSUE THREAD

**Issue by 4345dgfsd** [AzisPT/HaxRooms#1]
Hola, ¿puedo obtener un tutorial más detallado sobre cómo iniciar el script?

**Comment by AzisPT** [comment]
Necessitas de ter o Node.Js 16+ Instalado e uma Database MySQL 8.0+ Instalada, após esses simples processos baixas o script e modificas o ficheiro .env com os dados da tua base de dados (tens de criar uma base de dados no teu servidor MySQL e dar upload do ficheiro Database Limpa.sql), diriges-te até este site: [Token](https://www.haxball.com/headlesstoken) e colocas a token no room.ts na linha 136, e depois basta iniciar os .bat pela ordem indicada no readme.

**Comment by 4345dgfsd** [comment]
Hola, gracias por responder. He hecho todo lo que me ha dicho. Pero tengo este error, ¿cómo puedo solucionarlo? Gracias.
![Izrezak](https://github.com/AzisPT/HaxRooms/assets/49644683/a41cab82-12d1-4eab-9c1d-f19630be1e1d)

**Comment by AzisPT** [comment]
What's the MySQL version you have installed?

**Comment by 4345dgfsd** [comment]
8.0.37.0 for Windows

**Comment by AzisPT** [comment]
I wasn't able to reproduce the problem with the MySQL version 8.0.31.

But are you sure you only have 1 version of the MySql installed?

**Comment by AzisPT** [comment]
From what I think it can be, it can also be a problem with privileges in your account, try to create an account just for that purpose and put the name and password in the .env accordingly

**Comment by 4345dgfsd** [comment]
> I wasn't able to reproduce the problem with the MySQL version 8.0.31.
> 
> But are you sure you only have 1 version of the MySql installed?

I'll try download this version and try it out

**Comment by AzisPT** [comment]
> > I wasn't able to reproduce the problem with the MySQL version 8.0.31.
> > But are you sure you only have 1 version of the MySql installed?
> 
> I'll try download this version and try it out

I do not think it is a version problem but the mysql account you are using for the login has a permission problem or is configured incorrectly.

**Comment by 4345dgfsd** [comment]
> > > I wasn't able to reproduce the problem with the MySQL version 8.0.31.
> > > But are you sure you only have 1 version of the MySql installed?
> > 
> > 
> > I'll try download this version and try it out
> 
> I do not think it is a version problem but the mysql account you are using for the login has a permission problem or is configured incorrectly.

I went ahead and created a new account, named it server, gave it all permissions for every database and i keep on getting an error that says the password is incorrect. No matter how many times i changed the password and wrote it correctly in the .env file, it just says the same. 
![Izrezak](https://github.com/AzisPT/HaxRooms/assets/49644683/c901c7ca-4a4f-4935-a092-9efd0a6e7e21)
Thanks.

**Comment by AzisPT** [comment]
Run this command in the MySQL:

`ALTER USER 'server'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';`

In `password` put the password you want for the account.

After that run:

`flush privileges;`

**Comment by 4345dgfsd** [comment]
OMG, thank you very much! <3 <3
It worked, thank you. :D

*Also how can i get superadmin in the room?

**Comment by AzisPT** [comment]
> OMG, thank you very much! <3 <3 It worked, thank you. :D
> 
> *Also how can i get superadmin in the room?

To get superadmin in the room you first create an account and then go to the database table `players` column `superadmin` and switch from `0` to `1`.
