### ISSUE TITLE
Already logged in error

### ISSUE THREAD

**Issue by 4345dgfsd** [AzisPT/HaxRooms#3]
Hi there, me again lmao :D

So i realised this issue is pretty common, and it doesn't let the player join the room, instead it displays a "Connection closed" error on haxball, but on the cmd log it says that the player joined the room already, and because of the Anti-Double login feature, the player cannot join the room. When a player registers into the database, the next time, upon server restart, the player is usually met with this error. The only proper way to get rid of the error is to manually remove the player from the database, making them lose all stats and they have to register again. I tried to remove the Double login part of the script, but that breaks the code and the room does not work properly. 
Sorry for creating so many issues on this script, but this seems like a pretty serious problem.

In the database the player's label "LoggedIn" is changed to 1 so the room technically thinks the player is connected. If you change it back to 0 the person can join the room with no problem.

Once again, thank you for creating this amazing script!

**Comment by AzisPT** [comment]
Yes, what I usually did was just put the LoggedIn to a '0', it only happens if you close the room with players inside, from time to time a bug can happen where it stays with the '1' but it's rare, just manually switch to '0' you don't need to delete all the players stats.

**Comment by 4345dgfsd** [comment]
Yeah, i figured it out, thanks for responding :D
