### ISSUE TITLE
Statistics question

### ISSUE THREAD

**Issue by 4345dgfsd** [AzisPT/HaxRooms#5]
Hey man! Its me again, i joined your discord server and i was wondering how you set this website with statistics of the haxball room? Thanks in advance <3
![image-5](https://github.com/user-attachments/assets/793f5985-60ce-4ccb-b1d2-5d015d396e29)

**Comment by AzisPT** [comment]
Connected the database with the website and grabbed the information from there, simple PHP information, that project is old tho, I am now working on a new one :)

**Comment by 4345dgfsd** [comment]
Ahaaa, thanks <3
